### ISSUE TITLE
Doc site : Sidebar doen't scroll

### ISSUE THREAD

**Issue by chkube** [tynamo/tynamo.github.io#1]
Hello,
On the Home page of the project, I can't see the full sidebar menu on the left on my screen, and it doesn't scroll.
Thanks

**Comment by kaosko** [comment]
Thanks... still working on the layout, will get it fixed.

**Comment by kaosko** [comment]
Better? Let me know if not with a screenshot and the browser version.

**Comment by chkube** [comment]
Yes, it works fine now. Thanks.
