### ISSUE TITLE
Broken Links for Guides

### ISSUE THREAD

**Issue by dshields1** [tynamo/tynamo.github.io#2]
When I navigate to any of the pages that end in +guide from the apex domain I get a Server Error 404. The pages load fine when you add www, and all the other pages seem to work from the apex domain. A few of your other repositories link to these broken urls, like tapestry-model, tapestry-security, and tapestry-resteasy.

**Comment by kaosko** [comment]
Thanks for the issue, I've noticed. I've tried to retain the old Confluence-based urls. However, I can't put a CNAME from the naked tynamo.org domain to the github.io subdomain. I've set up forwarding from tynamo.org to www.tynamo.org but it baffles me why GoDaddy gives 404s for the urls with paths. Let me know if you know better. I fixed the urls in the readme's.
